ServerEvents.tags('item', event => {
  event.add('gtceu:circuits', 'kubejs:lv_universal_circuit')
  event.add('gtceu:circuits', 'kubejs:mv_universal_circuit')
  event.add('gtceu:circuits', 'kubejs:hv_universal_circuit')
  event.add('gtceu:circuits', 'kubejs:ev_universal_circuit')
  event.add('gtceu:circuits', 'kubejs:iv_universal_circuit')
  event.add('gtceu:circuits', 'kubejs:luv_universal_circuit')
  event.add('gtceu:circuits', 'kubejs:uv_universal_circuit')
  event.add('gtceu:circuits', 'kubejs:uhv_universal_circuit')
  event.add('gtceu:circuits', 'kubejs:uev_universal_circuit')
  event.add('gtceu:circuits', 'kubejs:uiv_universal_circuit')
  event.add('gtceu:circuits', 'kubejs:uxv_universal_circuit')
  event.add('gtceu:circuits', 'kubejs:opv_universal_circuit')

    event.add('gtceu:circuits/lv', 'kubejs:lv_universal_circuit')
    event.add('gtceu:circuits/mv', 'kubejs:mv_universal_circuit')
    event.add('gtceu:circuits/hv', 'kubejs:hv_universal_circuit')
    event.add('gtceu:circuits/ev', 'kubejs:ev_universal_circuit')
    event.add('gtceu:circuits/iv', 'kubejs:iv_universal_circuit')
    event.add('gtceu:circuits/luv', 'kubejs:luv_universal_circuit')
    event.add('gtceu:circuits/uv', 'kubejs:uv_universal_circuit')
    event.add('gtceu:circuits/uhv', 'kubejs:uhv_universal_circuit')
    event.add('gtceu:circuits/uev', 'kubejs:uev_universal_circuit')
    event.add('gtceu:circuits/uiv', 'kubejs:uiv_universal_circuit')
    event.add('gtceu:circuits/uxv', 'kubejs:uxv_universal_circuit')
    event.add('gtceu:circuits/opv', 'kubejs:opv_universal_circuit')
  })