ServerEvents.recipes(event =>{
event.remove({ id: 'minecraft:red_bed' })
event.remove({ id: 'minecraft:blue_bed' })
event.remove({ id: 'minecraft:light_blue_bed' })
event.remove({ id: 'minecraft:orange_bed' })
event.remove({ id: 'minecraft:green_bed' })
event.remove({ id: 'minecraft:black_bed' })
event.remove({ id: 'minecraft:light_gray_bed' })
event.remove({ id: 'minecraft:gray_bed' })
event.remove({ id: 'minecraft:brown_bed' })
event.remove({ id: 'minecraft:lime_bed' })
event.remove({ id: 'minecraft:cyan_bed' })
event.remove({ id: 'minecraft:pink_bed' })
event.remove({ id: 'minecraft:purple_bed' })
event.remove({ id: 'minecraft:magenta_bed' })
event.remove({ id: 'minecraft:white_bed' })
event.remove({ id: 'tempad:tempad' })
event.remove({ id: 'gtceu:chemical_bath/quantum_eye' })
event.remove({ id: 'ae2:network/cells/item_storage_components_cell_1k_part'})
event.remove({ id: 'ae2:network/cells/item_storage_components_cell_4k_part'})
event.remove({ id: 'ae2:network/cells/item_storage_components_cell_16k_part'})
event.remove({ id: 'ae2:network/cells/item_storage_components_cell_64k_part'})
event.remove({ id: 'ae2:network/cells/item_storage_components_cell_256k_part'})
event.remove({ id: 'ae2:network/cells/item_cell_housing'})
event.remove({ id: 'megacells:cells/cell_component_1m'})
event.remove({ id: 'megacells:cells/cell_component_4m'})
event.remove({ id: 'megacells:cells/cell_component_16m'})
event.remove({ id: 'megacells:cells/cell_component_64m'})
event.remove({ id: 'megacells:cells/cell_component_256m'})
event.remove({ id: 'megacells:inscriber/accumulation_processor'})
event.remove({ id: 'megacells:inscriber/accumulation_processor_print'})
event.remove({ id: 'solarflux:photovoltaic_cell_1'})
event.remove({ id: 'solarflux:photovoltaic_cell_2'})
event.remove({ id: 'solarflux:photovoltaic_cell_3'})
event.remove({ id: 'solarflux:photovoltaic_cell_4'})
event.remove({ id: 'solarflux:photovoltaic_cell_5'})
event.remove({ id: 'solarflux:photovoltaic_cell_6'})
event.remove({ id: 'draconicevolution:components/draconium_core'})
event.remove({ id: 'draconicevolution:components/wyvern_core'})
event.remove({ id: 'draconicevolution:components/awakened_core'})
event.remove({ id: 'draconicevolution:components/chaotic_core'})
event.remove({ id: 'draconicevolution:components/draconium_ingot_from_dust'})
event.remove({ id: 'draconicevolution:components/draconium_ingot_from_ore'})
event.remove({ type: 'draconicevolution:fusion_crafting'})
event.remove({ output: '#kubejs:wooden_tools'})
event.remove({ id: 'draconicevolution:machines/crafting_core'})
event.remove({ id: 'draconicevolution:basic_crafting_injector'})
})